OSRM:
    Server:
        Host: http://localhost:5000/route/v1/driving/
        Tail: ?overview=false
DB:
    # ConnectionString: Data Source=server1;Initial Catalog=Database1;Integrated Security=SSPI;
    # ConnectionString: Host=localhost;Database=moble;Username=postgres;Password=Vcc8tVfQRqmn4zfjM3wk
    # ConnectionString: Host=host.docker.internal;Database=mobble;Username=postgres;Password=Vcc8tVfQRqmn4zfjM3wk
    ConnectionString: Host=localhost;Database=mobble;Username=postgres;Password=Vcc8tVfQRqmn4zfjM3wk
    NumberOfDeadlockRepeats: 5
    DefaultTimeout: 00:05:00

# OSRM:
#   Server:
#     Host: ${OSRM_URL:-http://localhost:5000/route/v1/driving/}
#     Tail: ?overview=false
# DB:
# #   ConnectionString: ${ConnectionStrings__DefaultConnection:-Host=localhost;Database=mobble;Username=postgres;Password=your_popo_secure_password}
#   ConnectionString: Host=localhost;Database=mobble;Username=postgres;Password=your_popo_secure_password
# #   ConnectionString: Host=host.docker.internal;Database=mobble;Username=postgres;Password=your_popo_secure_password
#   NumberOfDeadlockRepeats: 5
#   DefaultTimeout: 00:05:00