# version: '3.8'

# services:
#   app:
#     build: .
#     ports:
#       - "8085:8085"
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       # - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Database=mobble;Username=postgres;Password=Vcc8tVfQRqmn4zfjM3wk
#       - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Database=mobble;Username=postgres;Password=Vcc8tVfQRqmn4zfjM3wk
#       - OSRM_URL=http://osrm:5000
#     networks:
#       - my_network
#     extra_hosts:
#       - "host.docker.internal:host-gateway"

# networks:
#   my_network:
#     external: true
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8085:8085"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Database=mobble;Username=postgres;Password=Vcc8tVfQRqmn4zfjM3wk
      - OSRM_URL=http://osrm:5000
    networks:
      - my_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  my_network:
    external: true